CREATE TABLE IF NOT EXISTS builder_form (
    x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    form_key CHAR(36) NOT NULL UNIQUE,
    branch_key CHAR(36) NOT NULL,
    project_key CHAR(36) NOT NULL,
    form_code VARCHAR(80) NOT NULL UNIQUE,
    form_name VARCHAR(160) NOT NULL,
    form_description TEXT NULL,
    form_table_name VARCHAR(100) NULL UNIQUE,
    form_schema_version INT UNSIGNED NOT NULL DEFAULT 1,
    form_status ENUM('DRAFT','ACTIVE','INACTIVE','ARCHIVED','DELETED') NOT NULL DEFAULT 'DRAFT',
    form_settings JSON NULL,
    server_timestamp TIMESTAMP NULL,
    form_created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    form_created_by_key CHAR(36) NULL,
    form_updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    form_updated_by_key CHAR(36) NULL,
    form_deleted_at TIMESTAMP NULL,
    form_deleted_by_key CHAR(36) NULL,
    INDEX idx_builder_form_branch (branch_key),
    INDEX idx_builder_form_project (project_key),
    INDEX idx_builder_form_status (form_status),
    INDEX idx_builder_form_table (form_table_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS builder_form_version (
    x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    version_key CHAR(36) NOT NULL UNIQUE,
    form_key CHAR(36) NOT NULL,
    version_number INT UNSIGNED NOT NULL,
    version_status ENUM('DRAFT','PUBLISHED','ARCHIVED','DELETED') NOT NULL DEFAULT 'DRAFT',
    schema_snapshot JSON NOT NULL,
    published_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by_key CHAR(36) NULL,
    UNIQUE KEY uq_builder_form_version_number (form_key, version_number),
    INDEX idx_builder_form_version_form (form_key),
    INDEX idx_builder_form_version_status (version_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS builder_form_field (
    x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    field_key CHAR(36) NOT NULL UNIQUE,
    form_key CHAR(36) NOT NULL,
    field_code VARCHAR(80) NOT NULL,
    field_name VARCHAR(160) NOT NULL,
    field_label VARCHAR(160) NOT NULL,
    field_type VARCHAR(60) NOT NULL,
    data_type VARCHAR(60) NOT NULL DEFAULT 'string',
    database_column_name VARCHAR(100) NOT NULL,
    field_sort_order INT UNSIGNED NOT NULL DEFAULT 0,
    field_status ENUM('DRAFT','ACTIVE','INACTIVE','DELETED') NOT NULL DEFAULT 'DRAFT',
    is_required TINYINT(1) NOT NULL DEFAULT 0,
    is_unique TINYINT(1) NOT NULL DEFAULT 0,
    is_searchable TINYINT(1) NOT NULL DEFAULT 0,
    is_sortable TINYINT(1) NOT NULL DEFAULT 0,
    default_value TEXT NULL,
    validation_rules JSON NULL,
    option_source JSON NULL,
    formula_expression TEXT NULL,
    field_settings JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_builder_form_field_code (form_key, field_code),
    UNIQUE KEY uq_builder_form_field_column (form_key, database_column_name),
    INDEX idx_builder_form_field_form (form_key),
    INDEX idx_builder_form_field_type (field_type),
    INDEX idx_builder_form_field_status (field_status),
    INDEX idx_builder_form_field_sort (form_key, field_sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS builder_form_layout (
    x_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    layout_key CHAR(36) NOT NULL UNIQUE,
    form_key CHAR(36) NOT NULL,
    version_key CHAR(36) NULL,
    layout_name VARCHAR(160) NOT NULL,
    layout_type ENUM('FORM','TABLE','DETAIL','PRINT','MOBILE') NOT NULL DEFAULT 'FORM',
    layout_status ENUM('DRAFT','ACTIVE','INACTIVE','DELETED') NOT NULL DEFAULT 'DRAFT',
    layout_schema JSON NOT NULL,
    layout_sort_order INT UNSIGNED NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_builder_form_layout_name (form_key, layout_name, layout_type),
    INDEX idx_builder_form_layout_form (form_key),
    INDEX idx_builder_form_layout_version (version_key),
    INDEX idx_builder_form_layout_status (layout_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
