<?php
declare(strict_types=1);

return [
    [
        'field_name' => 'x_id',
        'field_type' => 'BIGINT UNSIGNED AUTO_INCREMENT',
        'field_length' => null,
        'field_default' => null,
        'is_nullable' => 0,
        'is_required' => 1,
        'is_indexed' => 0,
        'index_name' => 'PRIMARY',
        'index_columns' => ['x_id'],
        'field_sort_order' => 10,
    ],
    [
        'field_name' => 'record_key',
        'field_type' => 'CHAR',
        'field_length' => '36',
        'field_default' => null,
        'is_nullable' => 0,
        'is_required' => 1,
        'is_indexed' => 1,
        'index_name' => 'uq_record_key',
        'index_columns' => ['record_key'],
        'field_sort_order' => 20,
    ],
    [
        'field_name' => 'branch_key',
        'field_type' => 'CHAR',
        'field_length' => '36',
        'field_default' => null,
        'is_nullable' => 0,
        'is_required' => 1,
        'is_indexed' => 1,
        'index_name' => 'idx_branch_project',
        'index_columns' => ['branch_key', 'project_key'],
        'field_sort_order' => 30,
    ],
    [
        'field_name' => 'project_key',
        'field_type' => 'CHAR',
        'field_length' => '36',
        'field_default' => null,
        'is_nullable' => 0,
        'is_required' => 1,
        'is_indexed' => 1,
        'index_name' => 'idx_branch_project',
        'index_columns' => ['branch_key', 'project_key'],
        'field_sort_order' => 40,
    ],
    [
        'field_name' => 'form_key',
        'field_type' => 'CHAR',
        'field_length' => '36',
        'field_default' => null,
        'is_nullable' => 0,
        'is_required' => 1,
        'is_indexed' => 1,
        'index_name' => 'idx_form_status',
        'index_columns' => ['form_key', 'record_status'],
        'field_sort_order' => 50,
    ],
    [
        'field_name' => 'record_status',
        'field_type' => "ENUM('DRAFT','PENDING','APPROVED','REJECTED','ACTIVE','INACTIVE','ARCHIVED','DELETED')",
        'field_length' => null,
        'field_default' => 'DRAFT',
        'is_nullable' => 0,
        'is_required' => 1,
        'is_indexed' => 1,
        'index_name' => 'idx_form_status',
        'index_columns' => ['form_key', 'record_status'],
        'field_sort_order' => 60,
    ],
    [
        'field_name' => 'server_timestamp',
        'field_type' => 'TIMESTAMP',
        'field_length' => null,
        'field_default' => null,
        'is_nullable' => 1,
        'is_required' => 1,
        'is_indexed' => 0,
        'index_name' => null,
        'index_columns' => null,
        'field_sort_order' => 70,
    ],
    [
        'field_name' => 'created_at',
        'field_type' => 'TIMESTAMP',
        'field_length' => null,
        'field_default' => 'CURRENT_TIMESTAMP',
        'is_nullable' => 0,
        'is_required' => 1,
        'is_indexed' => 1,
        'index_name' => 'idx_created_at',
        'index_columns' => ['created_at'],
        'field_sort_order' => 80,
    ],
    [
        'field_name' => 'created_by_key',
        'field_type' => 'CHAR',
        'field_length' => '36',
        'field_default' => null,
        'is_nullable' => 1,
        'is_required' => 1,
        'is_indexed' => 0,
        'index_name' => null,
        'index_columns' => null,
        'field_sort_order' => 90,
    ],
    [
        'field_name' => 'updated_at',
        'field_type' => 'TIMESTAMP',
        'field_length' => null,
        'field_default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
        'is_nullable' => 0,
        'is_required' => 1,
        'is_indexed' => 0,
        'index_name' => null,
        'index_columns' => null,
        'field_sort_order' => 100,
    ],
    [
        'field_name' => 'updated_by_key',
        'field_type' => 'CHAR',
        'field_length' => '36',
        'field_default' => null,
        'is_nullable' => 1,
        'is_required' => 1,
        'is_indexed' => 0,
        'index_name' => null,
        'index_columns' => null,
        'field_sort_order' => 110,
    ],
    [
        'field_name' => 'deleted_at',
        'field_type' => 'TIMESTAMP',
        'field_length' => null,
        'field_default' => null,
        'is_nullable' => 1,
        'is_required' => 1,
        'is_indexed' => 0,
        'index_name' => null,
        'index_columns' => null,
        'field_sort_order' => 120,
    ],
    [
        'field_name' => 'deleted_by_key',
        'field_type' => 'CHAR',
        'field_length' => '36',
        'field_default' => null,
        'is_nullable' => 1,
        'is_required' => 1,
        'is_indexed' => 0,
        'index_name' => null,
        'index_columns' => null,
        'field_sort_order' => 130,
    ],
];
